os: linux
dist: bionic
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - gm130s@gmail.com
env:
  jobs:
    - ROS_DISTRO="humble"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git -b master .ci_config
script:
  - source .ci_config/travis.sh
